#!/usr/bin/env escript
%% -*- erlang -*-

% -mode(compile).
% -compile(native).

%TODO: See utf-8 in Erlang, how to work?

main(_) ->
  {ok, ScriptDir} = file:get_cwd(),
  {ok, Listing} = file:list_dir_all(ScriptDir),
  Dirs = lists:filter(fun(A)->filelib:is_dir(A) end,Listing),
  io:format("~p~n", [Dirs]),
  erlang:halt(0).
