#!/usr/bin/env escript
%% -*- erlang -*-

-mode(compile).
-compile([nowarn_unused_vars, nowarn_unused_function]).

-define(ESC, <<"\e[">>).
-define(RST, <<"0">>).
-define(END, <<"m">>).

%% Defining colors
-define(YELLOW, <<"33">>).
-define(CYAN, <<"36">>).
-define(RED, <<"31">>).
-define(BLUE, <<"34">>).
-define(MAGENTA, <<"35">>).
-define(GREEN, <<"32">>).

%% Internal
color(Color) -> <<?ESC/binary, Color/binary, ?END/binary>>.
reset() -> <<?ESC/binary, ?RST/binary, ?END/binary>>.

%% Colors
yellow(Text) -> [color(?YELLOW), Text, reset()].
cyan(Text) -> [color(?CYAN), Text, reset()].
red(Text) -> [color(?RED), Text, reset()].
blue(Text) -> [color(?BLUE), Text, reset()].
magenta(Text) -> [color(?MAGENTA), Text, reset()].
green(Text) -> [color(?GREEN), Text, reset()].

info() ->
  io:format("~s~n", [yellow("What the task?")]),
  io:format("- ~s | ~s~n", [green("update <directory>"), cyan("Updating git repository of a specifical directory")]),
  io:format("- ~s | ~s~n", [green("updateall"), cyan("Updating git repository of all directories in path")]),
  io:format("- ~s | ~s~n", [green("clean <directory>"), cyan("Cleaning git repository of a specifical directory")]),
  io:format("- ~s | ~s~n", [green("cleanall"), cyan("Cleaning git repository of all directories in path")]).

update_git(Args) -> io:format("Updating Git").

main(Args) ->
  case(Args) of
    [] -> info();
    ["update", _] -> update_git(Args);
    Else -> info()
  end,
  erlang:halt(0).



  % io:format("~p~n", [Args]).

%   {ok, ScriptDir} = file:get_cwd(),
%   listing_dir(ScriptDir),
%   io:format("~p~n", [Dirs]),
  % erlang:halt(0).
%
% % Listing directories in this Directory
% listing_dir(Dir) ->
%   {ok, Listing} = file:list_dir_all(Dir),
%   Dirs = lists:filter(fun(A)->filelib:is_dir(A) end,Listing).
%
%
% % Update repository to all directories into
% update_git(Dir) ->
%   listing_dir(Dir).
%   %TODO: updating git

%TODO: How to get import functions from module external into escript
%TODO: See utf-8 in Erlang, how to work?
